import { handlers } from "@/auth";

/**
 * Exporting the GET and POST handlers generated by NextAuth.
 * This effectively sets up the /api/auth/* endpoints.
 */
export const { GET, POST } = handlers;
